### ISSUE TITLE
Extension for Asterix ChemStation

### ISSUE THREAD

**Issue by haeussma** [evanyeyeye/rainbow#13]
I tried to use you package to read in `.ch` files from Asterix ChemStation. However, there seems to be an issue with the scaling of the data in the data body. Is there a way to adjust `rainbow` to support data from Asterix ChemStation? How could one find out the scaling factor to read out the data body correctly?

**Comment by ekwan** [comment]
Not sure.  Do you have some sample data you can share?

**Comment by ekwan** [comment]
What's Asterix Chemstation?

**Comment by ekwan** [comment]
Thanks, we'll take a look.  Can you upload the entire .D folder?

**Comment by haeussma** [comment]
Added the `.D` folder to the drive. 
Thanks for looking into it!

**Comment by ekwan** [comment]
OK.  Do you know what the correct scaling is?  Do you have this decoded properly in some other format?  A screenshot of how it appears in ChemStation, preferably with some exact numbers?

**Comment by JMarvi3** [comment]
As far as I can tell, rainbow didn't know how to decode your files. I modified it to do so. There is a new version of rainbow on [PyPi](https://pypi.org/project/rainbow-api/1.0.7/).

Please let me know if this solves your issue.
