### ISSUE TITLE
lzf has no attribute decompress

### ISSUE THREAD

**Issue by DanielQuiroz97** [evanyeyeye/rainbow#14]
# Issue

I am using a  MAC with an M2 chip

I am trying to use the module `rainbow.agilent.masshunter.parse_msdata()` but I encounter the following error mesage:

```python

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[110], [line 1](vscode-notebook-cell:?execution_count=110&line=1)
----> [1](vscode-notebook-cell:?execution_count=110&line=1) profile = rainbow.agilent.masshunter.parse_msdata("Data/Agilent/MS1/QC_neg_5.d/AcqData")

AttributeError: module 'lzf' has no attribute 'decompress'
```

I succesfully intalled the `lzf` library (I think), but when I tried to call the `lzf.decompress()` module it just does not show up (Image bellow).

![Screenshot 2024-03-16 at 1 16 25 AM](https://github.com/evanyeyeye/rainbow/assets/18486943/52c8f8a4-52f0-41a6-8859-93d6ebd4b0bf)

Any recomendations to troubleshoot this issue?

**Comment by ekwan** [comment]
I think lzf and python-lzf are different. Please double check your
dependencies and let me know. The high res part of the library needs more
development.

**Comment by JMarvi3** [comment]
I can confirm that `python-lzf` has `decompress` and `lzf` does not.

**Comment by ekwan** [comment]
Okeydokey, closing...tldr, make sure you use python-lzf not lzf!
