### ISSUE TITLE
Scaling data issue for Agilent 7890A GC FID

### ISSUE THREAD

**Issue by denisshragin** [evanyeyeye/rainbow#15]
When trying to get a .csv file from the FID1A.ch file for GC-FID Agilent 7890A a get only 341 data points in the output.csv file, however the csv file exported with Agilent software (FID data) had 21084 rows.
Software GC Chemstation B.04.02 SP1.

This issue may be the same as in #13. 

Two files with an example are here:
https://drive.google.com/drive/folders/1pMSbtQUYjCvHe4gsaDTn1Qcsu0bGqNS7?usp=sharing

**Comment by ekwan** [comment]
Thanks!  Please include the entire .D folder.

**Comment by denisshragin** [comment]
The entire .D folder is added.

**Comment by ekwan** [comment]
Thanks!  We'll try to take a look next week.

**Comment by ekwan** [comment]
What was wrong?

**Comment by JMarvi3** [comment]
Rainbow was reading a certain number of absorbances instead of reading to the end of the file.
There is a new version on [PyPi](https://pypi.org/project/rainbow-api/1.0.7/).
Let me know if this fixes your issue or if it needs further attention.

**Comment by denisshragin** [comment]
For the moment I can confirm that a number of retention times match the number of times generated by the Agilent software. I need perform several tests for the signals intensities. I will take a look today or this week. 

But I have a small question: Is data obtained via Rainbow library are platform independent? (I get my chromatograms on Windows and I try to process them with MacOS 64 bits )

Thanks you for you support! I

**Comment by ekwan** [comment]
Yes, it should be platform independent.

**Comment by denisshragin** [comment]
I have tested the new version of rainbow with several files, and I can confirm that the signal intensities are the same as with Agilent export. There are a tiny differences in the retention times but this not affect the area calculations. The sum of all these differences (three 21084 rows of data) is about only 0.0034 s.
Thank you very much for your great work!
