### ISSUE TITLE
parse compound names and MS2 from waters

### ISSUE THREAD

**Issue by sardnar** [evanyeyeye/rainbow#16]
Hello,

Thank you very much for this work! it's the cleanest way to parse waters data. In waters .raw there is a file called _FUNC001.CMP that contains the compound names. I think it should be easy to parse this as an attribute and save also as csv while looping. Also there must be a file in .raw that contains MS2 reads. The reads it self may not be important, but the mapping between which parent mass and child mass is of interest. 

Thanks again!

**Comment by sardnar** [comment]
I am uploading small example here.
[example.raw.zip](https://github.com/evanyeyeye/rainbow/files/14898231/example.raw.zip)

If there is a way to add _FUNC001.CMP names to the metadata, it would be so useful.

**Comment by ekwan** [comment]
Thanks!  We'll look into this.

**Comment by sardnar** [comment]
Thanks a lot!
