### ISSUE TITLE
New to MS Analysis

### ISSUE THREAD

**Issue by yipy0005** [evanyeyeye/rainbow#20]
Hi, I'm the IT person for my lab and I have been tasked to obtained the detected masses and their intensities from a Agilent .D folder.

Could you provide me with the steps on how I could do so with Rainbow?

Thank you so much! :)

Best regards,
Yew Mun

**Comment by ekwan** [comment]
Hi Yew!  Welcome!  Have you taken a look at the README and documentation?  We're happy to help if that doesn't answer your questions.

**Comment by yipy0005** [comment]
Hi Eugene,

Thank you so much for your reply!

I have looked at the README and documentation and tried:
```
import rainbow as rb
datadir = rb.read("mydata.D")
datafile = datadir.get_file("MSD1.MS")
```

After that, what could I get the mz data and their intensities from the variable, `datafile`?

**Comment by ekwan** [comment]
Hi, have you checked out our tutorial?

https://rainbow-api.readthedocs.io/en/latest/tutorial.html

**Comment by yipy0005** [comment]
Yes, I have.

Would you be referring to this section:

```
times = datafile.xlabels
wavelengths = datafile.ylabels
absorbances = datafile.data
```

where `xlabels` are m/z values, `ylabels` are abundance values? 😊

**Comment by yipy0005** [comment]
Ah, I see! Thank you so much! I think I have no questions for now. I'm so happy that you are very responsive.

Have a good day! 😊

**Comment by ekwan** [comment]
Good luck!  Please feel free to reach out again if we can be helpful!

**Comment by yipy0005** [comment]
Hi, sorry but I have just a few more naive questions pertaining to the results.

I have tried to run this:

```
import rainbow as rb
datadir = rb.read("tests/inputs/green.D")
datafile = datadir.get_file("MSD1.MS")
```

For `datafile.xlabels`, there is an array of values from 0.04725 to 147.69308333333333.
For `datafile.ylabels`, there is 1 value in the array, which is 204.
And for `datafile.data`, there is an array of values from 146 to 70968.

If `xlabels`are m/z values, then a mass of 0.04725 doesn't correspond to any fragment.
Could I ask then, how should I understand the values of `xlabels`, `ylabels` and `data`?

Thank you!
