### ISSUE TITLE
More naive questions pertaining to MS results

### ISSUE THREAD

**Issue by yipy0005** [evanyeyeye/rainbow#21]
Hi, sorry but I have just a few more naive questions pertaining to the results.

I have tried to run this:

```
import rainbow as rb
datadir = rb.read("tests/inputs/green.D")
datafile = datadir.get_file("MSD1.MS")
```

For `datafile.xlabels`, there is an array of values from 0.04725 to 147.69308333333333.
For `datafile.ylabels`, there is 1 value in the array, which is 204.
And for `datafile.data`, there is an array of values from 146 to 70968.

If `xlabels`are m/z values, then a mass of 0.04725 doesn't correspond to any fragment.
Could I ask then, how should I understand the values of `xlabels`, `ylabels` and `data`?

Thank you!

_Originally posted by @yipy0005 in https://github.com/evanyeyeye/rainbow/issues/20#issuecomment-2057132359_

**Comment by ekwan** [comment]
From https://rainbow-api.readthedocs.io/en/latest/tutorial.html:

times = datafile.xlabels
wavelengths = datafile.ylabels
absorbances = datafile.data

If it's MS, then it's masses not wavelengths.  Looks like your data is from a SIM experiment.

**Comment by yipy0005** [comment]
Hi,

Yes, it's a SIM experiment. Is there any way I can process the `datafile.xlabels`, `datafile.ylabels` and `datafile.data` to provide a table of m/z vs intensity? 😊

**Comment by ekwan** [comment]
I think the best way to think of the rainbow output is as a data matrix.
The x axis is time, the y axis is mass, and the values are ion counts. The
labels are the row and column labels. So, you already have the table you
want. If you need an explicit table, you can always use pandas to convert
the numpy arrays to a dataframe and pass the labels to df.columns and
df.index.
