### ISSUE TITLE
Improper loading of Agilent Chemstation MS data with numpy>=2.0

### ISSUE THREAD

**Issue by MatTolladay** [evanyeyeye/rainbow#30]
Agilent Chemstation MS data fails to load properly due to changes to numpy typing. 
Line 653 of chemstation.py:
```
for i in range(num_times):
    stop_index = cur_index + pair_counts[i]
    np.add.at(
    data[i],
    mz_indices[cur_index:stop_index],
    int_values[cur_index:stop_index])
    cur_index = stop_index
```
In older versions of numpy (numpy<2.0) the `cur_index + pair_counts[i]` returns an `int` (the type of `cur_index`). Newer versions of numpy coerce it to the type of `pair_counts[i]` i.e. `np.int16`. This can cause an integer overflow warning and incorrect MS data

**Comment by ekwan** [comment]
Completed.
