### ISSUE TITLE
Can't use Rainbows to access Chemstation directory and HPLC datafiles. 

### ISSUE THREAD

**Issue by ddalland** [evanyeyeye/rainbow#5]
Thank you for providing this Python code, which I am hoping to use for a chemistry project. Unfortunately, it is not working for me so far. When I run the following cell in Jupyter notebook to read the Chemstation data in folder 55.D:
 "import rainbow as rb
datadir = rb.read('/Users/ (...) /VTNA-4/55.D')"
Datadir only contains a name '55.D' and the metadata: {'vendor': 'Agilent', 'vialpos': '55'}. When I then try to read one of my .ch files (datadir.get_file('dad1C.ch')), I get an error message saying that "Data file dad1C.ch not found in 55.D.". I have also tried to apply the method rb.agilent.chemstation.parse_ch('dad1C.ch'), but this returns None, suggesting that the file cannot be read. Do you know my rainbows is not working in my case? I can access the data using a program called UniChrom, but this is less useful than using Python. A colleague of mine has used rainbows successfully in the way I have attempted, but he has used data from a newer version of the chemstation software, maybe that makes the difference?

PS: the files in my directory 55.D are as follows:
['.ipynb_checkpoints',
 'ACQRES.REG',
 'dad1.uv',
 'dad1A.ch',
 'dad1B.ch',
 'dad1C.ch',
 'dad1D.ch',
 'dad1E.ch',
 'LCDIAG.REG',
 'Report.TXT',
 'Report00.CSV',
 'REPORT01.CSV',
 'REPORT02.CSV',
 'REPORT03.CSV',
 'REPORT04.CSV',
 'REPORT05.CSV',
 'RUN.LOG',
 'SAMPLE.MAC',
 'Untitled.ipynb']

**Comment by ekwan** [comment]
Would you be able to share the .D file as a zip so we can look at it?

**Comment by ddalland** [comment]
Yes, sure. Here it is along with another one in case that's useful. Thank you!
[55.D.zip](https://github.com/evanyeyeye/rainbow/files/13219631/55.D.zip)
[37.D.zip](https://github.com/evanyeyeye/rainbow/files/13219643/37.D.zip)

**Comment by ekwan** [comment]
My colleague James is looking into this and we will get back to you!

**Comment by ekwan** [comment]
We looked at this and it seems to be a different format.  What version of ChemStation are you using?  Are you able to provide a decoded version from UniChrom?

**Comment by ddalland** [comment]
Thank you for looking into it. The HPLC and chemstation software is of the old type (new at the time of Windows vista I think), but I don't know which format exactly, I can ask my colleagues and get back to you. I have sent pdf's, a csv and some screenshots showing what I got when I opened the .ch and .uv files in 55.D using UniChrom. 
[opened data.zip](https://github.com/evanyeyeye/rainbow/files/13221647/opened.data.zip)

**Comment by ekwan** [comment]
Hi!  Thanks very much!  Please give us a week or so to look at this.  We'll get back to you!

**Comment by ddalland** [comment]
Hi! Did you get time to have a look at it? I might need to find another solution if you didn't find a way around it. 
Thanks

**Comment by ekwan** [comment]
Sorry not yet. We can have a look this week.

**Comment by ekwan** [comment]
(It was Thanksgiving last week, so everyone was with their family.)

**Comment by ekwan** [comment]
Looks like we fixed the problem.  James will post here soon.  Have you got some more files we can test on?

**Comment by ddalland** [comment]
No worries! I hope thanksgiving was great. Thank you for working on it! Here are 4 HPLC sample files where I have opened 2 of the .ch files for each folder and saved the corresponding .csv files and report pdf files.
[Uploading HPLC data.zip…]()

**Comment by ekwan** [comment]
Thanks!  Something is wrong with that link...

**Comment by ddalland** [comment]
Woops, I hope this works: 
[HPLC data.zip](https://github.com/evanyeyeye/rainbow/files/13494014/HPLC.data.zip)

**Comment by ekwan** [comment]
Closed by PR #7.
